<?php

namespace App\Classes;

class SpellHelper {

	public function getSnippet($name) {
		if (strpos($name, '(') !== false) {
			$s = explode("(", $name);
			$name = trim($s[0]);
		}

		$spell = Cache::remember('spells_get_' . $name, 60, function () use ($name) {
			return Spell::where('name', $name)->first();
		});

		if ($spell) {
			return view('spell.snippet', compact('spell'))->render();
		} else {
			return null;
		}

	}

	public static function getSpellAbilities() {
		return [
			'intelligence' => 'Intelligence',
			'wisdom' => 'Wisdom',
			'charisma' => 'Charisma',
		];
	}

	public static function getClassSpellAbilities() {
		return [
			'Wizard' => 'Intelligence',
			'Rogue' => 'Intelligence',
			'Fighter' => 'Intelligence',
			'Cleric' => 'Wisdom',
			'Druid' => 'Wisdom',
			'Ranger' => 'Wisdom',
			'Bard' => 'Charisma',
			'Paladin' => 'Charisma',
			'Sorcerer' => 'Charisma',
			'Warlock' => 'Charisma',
		];
	}

	public static function getSpellLevels() {
		return [
			'0-level (Cantrip)' => '0-level (Cantrip)',
			'1st-level' => '1st-level',
			'2nd-level' => '2nd-level',
			'3rd-level' => '3rd-level',
			'4th-level' => '4th-level',
			'5th-level' => '5th-level',
			'6th-level' => '6th-level',
			'7th-level' => '7th-level',
			'8th-level' => '8th-level',
			'9th-level' => '9th-level',
		];
	}

	public static function getSpellSchools() {
		return [
			'Conjuration' => 'Conjuration',
			'Abjuration' => 'Abjuration',
			'Divination' => 'Divination',
			'Enchantment' => 'Enchantment',
			'Evocation' => 'Evocation',
			'Illusion' => 'Illusion',
			'Necromancy' => 'Necromancy',
			'Transmutation' => 'Transmutation',
		];
	}

	public static function getSpellClasses() {
		return [
			'Bard' => 'Bard',
			'Cleric' => 'Cleric',
			'Druid' => 'Druid',
			'Paladin' => 'Paladin',
			'Ranger' => 'Ranger',
			'Sorcerer' => 'Sorcerer',
			'Warlock' => 'Warlock',
			'Wizard' => 'Wizard',
		];
	}

	public static function getSpellComponents() {
		return [
			'V' => 'Verbal',
			'S' => 'Somatic',
			'M' => 'Material',
		];
	}

	public static function getSpellsKnown($class, $level, $spell_ability) {
		if ($class == 'Bard') {
			$spells_known = [
				'1' => '4',
				'2' => '5',
				'3' => '6',
				'4' => '7',
				'5' => '8',
				'6' => '9',
				'7' => '10',
				'8' => '11',
				'9' => '12',
				'10' => '14',
				'11' => '15',
				'12' => '15',
				'13' => '16',
				'14' => '18',
				'15' => '19',
				'16' => '19',
				'17' => '20',
				'18' => '22',
				'19' => '22',
				'20' => '22',
			];

			return $spells_known[$level];

		} elseif ($class == 'Cleric' || $class == 'Druid' || $class == 'Wizard') {
			if (($level + $spell_ability) > 0) {
				return $level + $spell_ability;
			} else {
				return 1;
			}
		} elseif ($class == 'Paladin') {
			if (($level + $spell_ability) > 0) {
				return floor($level / 2) + $spell_ability;
			} else {
				return 1;
			}
		} elseif ($class == 'Ranger') {
			$spells_known = [
				'1' => '-',
				'2' => '2',
				'3' => '3',
				'4' => '3',
				'5' => '4',
				'6' => '4',
				'7' => '5',
				'8' => '5',
				'9' => '6',
				'10' => '6',
				'11' => '7',
				'12' => '7',
				'13' => '8',
				'14' => '8',
				'15' => '9',
				'16' => '9',
				'17' => '10',
				'18' => '10',
				'19' => '11',
				'20' => '11',
			];

			return $spells_known[$level];

		} elseif ($class == 'Sorcerer') {
			$spells_known = [
				'1' => '2',
				'2' => '3',
				'3' => '4',
				'4' => '5',
				'5' => '6',
				'6' => '7',
				'7' => '8',
				'8' => '9',
				'9' => '10',
				'10' => '11',
				'11' => '12',
				'12' => '12',
				'13' => '13',
				'14' => '13',
				'15' => '14',
				'16' => '14',
				'17' => '15',
				'18' => '15',
				'19' => '15',
				'20' => '15',
			];

			return $spells_known[$level];

		} elseif ($class == 'Warlock') {
			$spells_known = [
				'1' => '2',
				'2' => '3',
				'3' => '4',
				'4' => '5',
				'5' => '6',
				'6' => '7',
				'7' => '8',
				'8' => '9',
				'9' => '10',
				'10' => '10',
				'11' => '11',
				'12' => '11',
				'13' => '12',
				'14' => '12',
				'15' => '13',
				'16' => '13',
				'17' => '14',
				'18' => '14',
				'19' => '15',
				'20' => '15',
			];

			return $spells_known[$level];

		} else {
			return 0;
		}
	}

	public static function checkSpellcaster($class) {
		if (array_key_exists($class, \SpellHelper::getSpellClasses())) {
			return true;
		} else {
			return false;
		}
	}

	public static function checkMultiSpellcaster($classes) {

		$i = 0;

		foreach ($classes as $class) {
			if (array_key_exists($class['name'], \SpellHelper::getSpellClasses())) {
				$i++;
			}
		}

		if ($i > 1) {
			return true;
		} else {
			return false;
		}

	}

	public static function getMultiSpellLevel($classes) {
		$level = 0;
		foreach ($classes as $class) {
			if (array_key_exists($class['name'], \SpellHelper::getSpellClasses())) {
				if ($class['name'] == 'Ranger' || $class['name'] == 'Paladin') {
					$level = $level + floor($class['level'] / 2);
				} elseif ($class['name'] != 'Warlock') {
					$level = $level + $class['level'];
				}
			}
		}

		return $level;

	}

	public static function getMultiSpellSlots($level = 1) {
		if ($level == null) {
			$level = 1;
		}

		$spell_slots = [
			'1' => [
				'1st-level' => '2',
				'2nd-level' => '0',
				'3rd-level' => '0',
				'4th-level' => '0',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'2' => [
				'1st-level' => '3',
				'2nd-level' => '0',
				'3rd-level' => '0',
				'4th-level' => '0',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'3' => [
				'1st-level' => '4',
				'2nd-level' => '2',
				'3rd-level' => '0',
				'4th-level' => '0',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'4' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '0',
				'4th-level' => '0',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'5' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '2',
				'4th-level' => '0',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'6' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '0',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'7' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '1',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'8' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '2',
				'5th-level' => '0',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'9' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '1',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'10' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '0',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'11' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'12' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '0',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'13' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '1',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'14' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '1',
				'8th-level' => '0',
				'9th-level' => '0',
			],
			'15' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '1',
				'8th-level' => '1',
				'9th-level' => '0',
			],
			'16' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '1',
				'8th-level' => '1',
				'9th-level' => '0',
			],
			'17' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '2',
				'6th-level' => '1',
				'7th-level' => '1',
				'8th-level' => '1',
				'9th-level' => '1',
			],
			'18' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '3',
				'6th-level' => '1',
				'7th-level' => '1',
				'8th-level' => '1',
				'9th-level' => '1',
			],
			'19' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '3',
				'6th-level' => '2',
				'7th-level' => '1',
				'8th-level' => '1',
				'9th-level' => '1',
			],
			'20' => [
				'1st-level' => '4',
				'2nd-level' => '3',
				'3rd-level' => '3',
				'4th-level' => '3',
				'5th-level' => '3',
				'6th-level' => '2',
				'7th-level' => '2',
				'8th-level' => '1',
				'9th-level' => '1',
			],
		];

		if ($level > 20) {
			return $spell_slots['20'];
		}

		return $spell_slots[$level];
	}

	public static function getSpellSlots($class, $level = 1) {
		if ($level == null) {
			$level = 1;
		}

		if ($class == 'Wizard') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'18' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'19' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'20' => [
					'0-level (Cantrip)' => '5',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '2',
					'8th-level' => '1',
					'9th-level' => '1',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Cleric') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'18' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'19' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'20' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '2',
					'8th-level' => '1',
					'9th-level' => '1',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Druid') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'18' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'19' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'20' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '2',
					'8th-level' => '1',
					'9th-level' => '1',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Ranger') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'18' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'19' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'20' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Bard') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'18' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'19' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'20' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '2',
					'8th-level' => '1',
					'9th-level' => '1',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Paladin') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'18' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'19' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'20' => [
					'0-level (Cantrip)' => '0',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Sorcerer') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '3',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '4',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '1',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '1',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '2',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'18' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '1',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'19' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '1',
					'8th-level' => '1',
					'9th-level' => '1',
				],
				'20' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '4',
					'2nd-level' => '3',
					'3rd-level' => '3',
					'4th-level' => '3',
					'5th-level' => '3',
					'6th-level' => '2',
					'7th-level' => '2',
					'8th-level' => '1',
					'9th-level' => '1',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} elseif ($class == 'Warlock') {
			$spell_slots = [
				'1' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '1',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'2' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '2',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'3' => [
					'0-level (Cantrip)' => '2',
					'1st-level' => '0',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'4' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '0',
					'2nd-level' => '2',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'5' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'6' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '2',
					'4th-level' => '0',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'7' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'8' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '2',
					'5th-level' => '0',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'9' => [
					'0-level (Cantrip)' => '3',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'10' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '2',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'11' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '3',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'12' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '3',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'13' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '3',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'14' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '3',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'15' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '3',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'16' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '3',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'17' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '4',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'18' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '4',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'19' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '4',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
				'20' => [
					'0-level (Cantrip)' => '4',
					'1st-level' => '0',
					'2nd-level' => '0',
					'3rd-level' => '0',
					'4th-level' => '0',
					'5th-level' => '4',
					'6th-level' => '0',
					'7th-level' => '0',
					'8th-level' => '0',
					'9th-level' => '0',
				],
			];

			if ($level > 20) {
				return $spell_slots['20'];
			}

			return $spell_slots[$level];

		} else {
			return "None";
		}
	}

	public static function getRedditMarkdown($spell) {
		$components = $spell->components . " " . ($spell->material ? '(' . $spell->material . ')' : '');

		$output = "#### [" . $spell->name . "](" . url('spell', $spell->id) . ")
		*" . ucfirst($spell->level) . ", " . $spell->school . "*";

		$output .= "
		&#010;
		**Casting Time:** " . $spell->casting_time . "&#010;
		**Range:** " . $spell->range . "&#010;
		**Components:** " . $components . "&#010;
		**Duration:** " . $spell->duration . "&#010;&#010;";

		$output .= Common::redditDescription($spell->description);

		if ($spell->higher_level) {
			$output .= "&#010;&#010;**At Higher Levels** &#010;&#010;" . $spell->higher_level;
		}

		return str_replace("\t", '', $output);

	}

	public static function getHomebreweryMarkdown($spell) {
		$components = $spell->components . " " . ($spell->material ? '(' . $spell->material . ')' : '');

		$output = "#### " . $spell->name . "
		*" . ucfirst($spell->level) . ", " . $spell->school . "*";

		$output .= "
		___
		- **Casting Time:** " . $spell->casting_time . "
		- **Range:** " . $spell->range . "
		- **Components:** " . $components . "
		- **Duration:** " . $spell->duration . "\r\r\n";

		$output .= Common::redditDescription($spell->description);

		if ($spell->higher_level) {
			$output .= "\r\r\n___ \r\r\n- **At Higher Levels** " . $spell->higher_level;
		}

		return str_replace("\t", '', $output);
	}

}